name: Multiple Worlflow Run

on:
  workflow_dispatch:

jobs:
  job-a:
    runs-on: macos-12
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: echo hello
        run: echo hello
  job-b:
    runs-on: macos-12
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: echo world
        run: echo world
      - name: echo hoge
        run: echo hoge
  job-c:
    runs-on: macos-12
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: echo fuga
        run: echo fuga
      - name: echo wawawa
        run: echo wawawa


